events{}

http{
	server {

		listen 80;
		listen [::]:80;
		server_name sramis-c.42.fr www.sramis-c.42.fr;
		server_name default_server;
		return 301 https://$host$request_uri;
	}

	server{
		listen 443 ssl;
		listen [::]:443 ssl;
		server_name sramis-c.42.fr;
		server_name default_server;

        ssl_certificate /etc/nginx/certs/server.crt;
        ssl_certificate_key /etc/nginx/certs/server.key;

		root /var/www/wordpress;
		index index.php index.html index.htm;

		ssl_protocols TLSv1.2 TLSv1.3;
		
		autoindex off;
		location ~ \.php$ {
			include fastcgi_params;
			fastcgi_intercept_errors on;
			fastcgi_pass wordpress:9000;
		fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
		}
	}

}