version: '3.8'

services:

  nginx:
    build:
      context: requirements/nginx
      dockerfile: Dockerfile
    ports:
      - "8443:443"
    env_file:
      - .env
    volumes:
      - /home/sramis-c/42/data/:/var/www/wordpress
    networks:
      - wordpress_net

  wordpress:
    build:
      context: requirements/wordpress
      dockerfile: Dockerfile
    ports:
      - "9000:9000"  # Expose port for PHP-FPM
    volumes:
      - wordpress_data:/var/www/wordpress
    networks:
      - wordpress_net

  mariadb:
    build:
      context: requirements/mariadb
      dockerfile: Dockerfile
    env_file: ".env"
    ports:
      - "3306:3306"  # Expose port for MariaDB
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./requirements/mariadb/conf/init.sh:/init.sh
    networks:
      - wordpress_net
    #restart: on-failure


volumes:
  wordpress_data:
  mariadb_data:

networks:
  wordpress_net:
    driver: bridge